import Link from 'next/link'
import { ArrowLeft, ArrowRight, CalendarDays } from 'lucide-react'
import { Logo, Navbar, WhatsAppButton } from '@/components/mtl-site'

const posts = [
  { category: 'Business technology', title: 'A practical guide to moving your SME to the cloud', excerpt: 'The signals that tell you it is time to modernise your infrastructure.' },
  { category: 'Cybersecurity', title: 'Five everyday habits that keep business data safer', excerpt: 'Simple, repeatable steps for teams without a dedicated security department.' },
  { category: 'Digital growth', title: 'Why your local business needs a digital front door', excerpt: 'How a clear web presence builds trust before the first conversation.' },
]
export default function BlogPage() { return <div className="min-h-screen bg-white"><Navbar /><main><section className="bg-slate-50 px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#2563EB]"><ArrowLeft className="size-4" /> Back to homepage</Link><div className="mt-14 max-w-2xl"><p className="eyebrow">MTL insights</p><h1 className="section-title">Useful thinking for the digital road ahead.</h1><p className="mt-6 text-lg leading-8 text-slate-600">Ideas, guides, and grounded perspectives from our team on technology, business, and building in Tanzania.</p></div></div></section><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-6 md:grid-cols-3">{posts.concat([{ category: 'Business systems', title: 'What to look for in a business management system', excerpt: 'The right system should create clarity, not another layer of work.' }]).map((post, index) => <article key={post.title} className="flex min-h-[330px] flex-col rounded-3xl border border-slate-200 bg-white p-7"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#0D9488]">{post.category}</span><span className="flex items-center gap-1 text-xs text-slate-400"><CalendarDays className="size-3.5" /> 06 Sep 2026</span></div><h2 className="mt-10 text-2xl font-bold tracking-tight text-slate-900">{post.title}</h2><p className="mt-4 flex-1 text-sm leading-7 text-slate-500">{post.excerpt}</p><button className="mt-7 inline-flex items-center gap-2 self-start text-sm font-bold text-[#2563EB]">Read article <ArrowRight className="size-4" /></button></article>)}</div></section></main><footer className="border-t border-slate-200 py-8 text-center text-sm text-slate-400">© 2026 Manyusi Technologies Limited</footer><WhatsAppButton /></div> }
