import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, Globe2, Mail, MessageCircle } from 'lucide-react'
import { ProfileDownload } from '@/components/profile-download'

export const metadata = { title: 'Company Profile | Manyusi Technologies Limited', description: 'The complete company profile for Manyusi Technologies Limited, led by Engineer Manyusi Asimwe.' }

const services = [
  ['Web & Mobile App Development', 'We design and build fast, intuitive digital products for organisations ready to serve customers better.', 'Websites, business portals, dashboards, Android and iOS applications, integrations.'],
  ['Networking Solutions', 'We create dependable office and campus networks that keep teams connected and productive.', 'LAN/WAN design, structured cabling, Wi-Fi, network security, documentation.'],
  ['Cybersecurity Services', 'We help teams understand risk, protect sensitive information, and respond with confidence.', 'Vulnerability assessments, security audits, firewall configuration, data protection guidance.'],
  ['Cloud Computing', 'We move the right workloads to the cloud with a practical focus on continuity, cost, and performance.', 'Cloud migration, hosting, backups, disaster recovery, infrastructure setup.'],
  ['CCTV Installation & Surveillance', 'We give organisations clearer visibility across their premises with integrated, easy-to-manage systems.', 'Camera planning, installation, remote monitoring, access and surveillance integration.'],
  ['Graphic Design', 'We turn business ideas into a consistent visual identity that people recognise and trust.', 'Logos, brand systems, presentations, marketing materials, business collateral.'],
  ['Digital Marketing', 'We help brands earn attention and turn online activity into measurable business conversations.', 'Social media, SEO, content marketing, campaigns, reporting and optimisation.'],
  ['ICT Training', 'We build confident teams through relevant, hands-on learning designed around real work.', 'Corporate programmes, software workshops, student training, digital skills enablement.'],
]
const values = [['Innovation', 'We keep learning and choose technology that creates useful progress.'], ['Reliability', 'We communicate clearly, deliver carefully, and remain available after launch.'], ['Integrity', 'We build relationships on honesty, responsibility, and respect for every client.'], ['Customer-centricity', 'We start with the business need, not a one-size-fits-all technology answer.']]

export default function CompanyProfilePage() {
  return <main className="min-h-screen bg-white text-[#1E293B] print:bg-white"><div className="mx-auto max-w-6xl px-5 py-8 md:px-10 md:py-12"><div className="flex items-center justify-between gap-4 print:hidden"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-[#2563EB]"><ArrowLeft className="size-4" /> Back to website</Link><ProfileDownload /></div>
    <header className="relative mt-12 overflow-hidden rounded-[2rem] bg-[#0f2c67] px-6 py-10 text-white md:mt-16 md:px-12 md:py-14"><div className="relative z-10 max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-blue-200">Official company profile · 2026</p><h1 className="mt-5 text-5xl font-black tracking-[-.06em] md:text-7xl">Manyusi Technologies Limited</h1><p className="mt-6 max-w-xl text-xl leading-8 text-blue-100">Powering businesses through technology.</p><p className="mt-8 max-w-2xl leading-7 text-blue-100/80">A Tanzanian ICT partner helping businesses, institutions, and growing teams operate smarter, stay secure, and build for what is next.</p></div><div className="mt-10 overflow-hidden rounded-3xl border border-white/20 md:absolute md:bottom-8 md:right-8 md:mt-0 md:w-80"><Image src="/mtl-hero.png" alt="Manyusi Technologies team collaborating in Dar es Salaam" width={1280} height={800} className="h-48 w-full object-cover" priority /></div></header>
    <section className="grid gap-10 border-b border-slate-200 py-16 md:grid-cols-[1.2fr_.8fr] md:py-20"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0D9488]">Executive summary</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-900 md:text-4xl">Technology that fits the way Tanzania does business.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Manyusi Technologies Limited is a full-service ICT company based in Dar es Salaam. We bring software, infrastructure, security, creative services, marketing, and training together under one dependable partner.</p><p className="mt-4 leading-7 text-slate-600">Our work is guided by a simple promise: make technology clear, useful, and sustainable for the people who rely on it every day.</p></div><div className="rounded-3xl bg-slate-50 p-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Company snapshot</p><div className="mt-6 grid gap-5 text-sm"><div><span className="font-bold text-slate-900">Head office</span><p className="mt-1 text-slate-500">Dar es Salaam, Tanzania</p></div><div><span className="font-bold text-slate-900">Leadership</span><p className="mt-1 text-slate-500">Engineer Manyusi Asimwe, Founder & CEO</p></div><div><span className="font-bold text-slate-900">Engagement model</span><p className="mt-1 text-slate-500">Project delivery, retainers, training and support</p></div></div></div></section>
    <section className="grid gap-10 border-b border-slate-200 py-16 md:grid-cols-[.8fr_1.2fr] md:py-20"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Our history</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-900">Built from a belief in local capability.</h2><p className="mt-5 leading-7 text-slate-600">Our company story is shaped by the needs we see around us: businesses need systems that work in real conditions, advice they can understand, and a partner who stays close to the outcome.</p></div><div className="grid gap-6 border-l-2 border-blue-100 pl-6"><div><p className="text-sm font-black text-[#2563EB]">The beginning</p><h3 className="mt-1 text-lg font-bold text-slate-900">A practical ICT vision</h3><p className="mt-2 text-sm leading-6 text-slate-500">Founded by Engineer Manyusi Asimwe, MTL began with a clear ambition: make dependable technology accessible to Tanzanian organisations.</p></div><div><p className="text-sm font-black text-[#0D9488]">Growing capability</p><h3 className="mt-1 text-lg font-bold text-slate-900">From projects to partnerships</h3><p className="mt-2 text-sm leading-6 text-slate-500">As client needs expanded, our capabilities grew across software, networks, cybersecurity, cloud, creative communication, and skills development.</p></div><div><p className="text-sm font-black text-[#F59E0B]">Today and ahead</p><h3 className="mt-1 text-lg font-bold text-slate-900">Building systems for lasting growth</h3><p className="mt-2 text-sm leading-6 text-slate-500">Today, MTL is developing integrated solutions such as MTL SmartBiz Suite while continuing to support organisations at every stage of their digital journey.</p></div></div></section>
    <section className="grid gap-5 py-16 md:grid-cols-2 md:py-20"><div className="rounded-3xl bg-blue-50 p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Mission</p><h2 className="mt-4 text-2xl font-bold text-slate-900">To empower businesses through accessible, reliable, and innovative technology solutions.</h2><p className="mt-5 leading-7 text-slate-600">We translate complex technology into confident action, helping teams become more productive and resilient.</p></div><div className="rounded-3xl bg-teal-50 p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0D9488]">Vision</p><h2 className="mt-4 text-2xl font-bold text-slate-900">A digitally confident Tanzania where every organisation can grow with technology.</h2><p className="mt-5 leading-7 text-slate-600">We see a future where local businesses compete, serve, and innovate at a global standard.</p></div></section>
    <section className="border-t border-slate-200 py-16 md:py-20"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0D9488]">What guides us</p><h2 className="mt-4 text-3xl font-bold text-slate-900">Our core values</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([title, copy]) => <div key={title} className="rounded-2xl border border-slate-200 p-6"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-sm font-black text-[#2563EB]">{title[0]}</div><h3 className="mt-5 font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div></section>
    <section className="grid gap-10 border-t border-slate-200 py-16 md:grid-cols-[.8fr_1.2fr] md:py-20"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Leadership</p><h2 className="mt-4 text-3xl font-bold text-slate-900">Engineer Manyusi Asimwe</h2><p className="mt-2 font-semibold text-[#0D9488]">Founder & Chief Executive Officer</p><p className="mt-5 leading-7 text-slate-600">Engineer Manyusi Asimwe leads MTL with an engineering mindset and an entrepreneurial understanding of business. His focus is on building practical capability: technology that improves the day-to-day and creates room for growth.</p></div><div className="overflow-hidden rounded-3xl"><Image src="/mtl-projects.png" alt="Technology infrastructure and digital systems representing MTL capabilities" width={1280} height={800} className="h-72 w-full object-cover" /></div></section>
    <section className="border-t border-slate-200 py-16 md:py-20"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Our services</p><h2 className="mt-4 text-3xl font-bold text-slate-900 md:text-4xl">One partner for your complete technology journey.</h2><p className="mt-5 leading-7 text-slate-600">Every service is designed to stand on its own or work as part of a wider transformation programme.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2">{services.map(([title, copy, deliverables], index) => <article key={title} className="rounded-2xl border border-slate-200 p-6 transition hover:border-blue-200 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 font-mono text-sm font-bold text-[#2563EB]">0{index + 1}</span><Check className="size-5 text-[#0D9488]" /></div><h3 className="mt-5 text-xl font-bold text-slate-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p><p className="mt-5 border-t border-slate-100 pt-4 text-sm leading-6 text-slate-500"><span className="font-bold text-slate-900">Typical scope: </span>{deliverables}</p></article>)}</div></section>
    <section className="grid gap-10 rounded-[2rem] bg-[#0f2c67] p-7 text-white md:grid-cols-[1fr_1.1fr] md:p-12"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-200">Flagship product</p><h2 className="mt-4 text-4xl font-black tracking-tight">MTL SmartBiz Suite</h2><p className="mt-5 leading-7 text-blue-100">Our full-stack business management system helps Tanzanian SMEs bring inventory, sales, invoicing, reporting, and multi-branch operations into one clear workspace.</p><Link href="/#products" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#F59E0B] px-5 py-3 text-sm font-bold text-slate-950">Request a demo <ArrowRight className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2">{['Inventory visibility', 'Sales and invoicing', 'Business reporting', 'Multi-branch support'].map((item) => <div key={item} className="rounded-2xl border border-white/15 bg-white/10 p-5"><Check className="size-5 text-[#F59E0B]" /><p className="mt-4 font-bold">{item}</p></div>)}</div></section>
    <section className="grid gap-10 border-b border-slate-200 py-16 md:grid-cols-[1fr_1.2fr] md:py-20"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0D9488]">How we work</p><h2 className="mt-4 text-3xl font-bold text-slate-900">Clear from first conversation to long-term support.</h2></div><div className="grid gap-5 sm:grid-cols-2">{['Consultation & discovery', 'Proposal & planning', 'Development & implementation', 'Support & maintenance'].map((item, index) => <div key={item} className="rounded-2xl bg-slate-50 p-5"><span className="font-mono text-sm font-bold text-[#2563EB]">0{index + 1}</span><h3 className="mt-3 font-bold text-slate-900">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-500">A transparent, collaborative step focused on measurable progress.</p></div>)}</div></section>
    <section className="py-16 md:py-20"><div className="rounded-[2rem] border border-blue-100 bg-blue-50 p-7 md:flex md:items-center md:justify-between md:gap-10 md:p-10"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2563EB]">Let us work together</p><h2 className="mt-3 text-3xl font-bold text-slate-900">Ready to make technology work harder for your organisation?</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Talk to our team about your next project, infrastructure need, training programme, or digital growth goal.</p></div><Link href="/#contact" className="mt-7 inline-flex shrink-0 items-center gap-2 rounded-full bg-[#2563EB] px-6 py-3 text-sm font-bold text-white md:mt-0">Contact MTL <ArrowRight className="size-4" /></Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Globe2 className="size-4 text-[#2563EB]" /> Dar es Salaam, Tanzania</span><span className="inline-flex items-center gap-2"><Mail className="size-4 text-[#2563EB]" /> hello@manyusitech.co.tz</span><span className="inline-flex items-center gap-2"><MessageCircle className="size-4 text-[#0D9488]" /> +255 700 000 000</span></div></section>
    <footer className="flex flex-col gap-4 border-t border-slate-200 pt-6 text-sm text-slate-500 md:flex-row md:items-center md:justify-between"><span>© 2026 Manyusi Technologies Limited. All rights reserved.</span><Link href="/" className="font-bold text-[#2563EB]">Back to website <ArrowRight className="ml-1 inline size-4" /></Link></footer>
  </div></main>
}
