import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, Clock3, GraduationCap } from 'lucide-react'
import { Logo, Navbar, WhatsAppButton } from '@/components/mtl-site'

const tracks = [
  ['Web Development Bootcamp', '8 weeks', 'Build responsive websites and the foundations of modern web applications.', ['HTML, CSS & JavaScript', 'React fundamentals', 'A guided portfolio project']],
  ['Networking & Security', '6 weeks', 'Understand the infrastructure that keeps teams connected and systems safer.', ['Network essentials', 'Security principles', 'Hands-on troubleshooting']],
  ['Digital Marketing', '4 weeks', 'Turn your online presence into a practical channel for reach and growth.', ['Content strategy', 'SEO foundations', 'Social campaign planning']],
  ['Office ICT Skills', '3 weeks', 'Help your team work faster and more confidently with everyday tools.', ['Microsoft Office', 'Digital collaboration', 'Data and file hygiene']],
]
export default function TrainingPage() { return <div className="min-h-screen bg-white"><Navbar /><main><section className="bg-[#eff6ff] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#2563EB]"><ArrowLeft className="size-4" /> Back to Manyusi</Link><div className="mt-14 max-w-3xl"><p className="eyebrow">MTL Academy</p><h1 className="section-title max-w-2xl">Practical skills for a more confident digital future.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Short, focused training programs for students, institutions, and teams who want to use technology with more confidence and create more opportunity.</p></div></div></section><section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-5 md:grid-cols-2">{tracks.map(([title, duration, copy, bullets]) => <article key={title} className="rounded-3xl border border-slate-200 p-7 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-100/50"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-xl bg-blue-50 text-[#2563EB]"><GraduationCap className="size-5" /></span><span className="inline-flex items-center gap-1 rounded-full bg-slate-50 px-3 py-1 text-xs font-bold text-slate-500"><Clock3 className="size-3.5" /> {duration}</span></div><h2 className="mt-8 text-2xl font-bold tracking-tight text-slate-900">{title}</h2><p className="mt-3 leading-7 text-slate-500">{copy}</p><ul className="mt-6 flex flex-col gap-3">{(bullets as string[]).map((bullet) => <li key={bullet} className="flex items-center gap-2 text-sm font-medium text-slate-700"><Check className="size-4 text-[#0D9488]" /> {bullet}</li>)}</ul><Link href="/#contact" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#2563EB] px-5 py-3 text-sm font-bold text-white">Enroll now <ArrowRight className="size-4" /></Link></article>)}</div></section></main><footer className="border-t border-slate-200 py-8 text-center text-sm text-slate-400">© 2026 Manyusi Technologies Limited</footer><WhatsAppButton /></div> }
